import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import Image from 'next/image';
import PlayButton from '@/components/PlayButton/PlayButton.component';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <Image src='/img/logo.png' alt='logo.png' width={464} height={217} />
        <PlayButton />
      </main>
    </>
  );
}
